// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// RefreshButton renders a refresh button with auto-refresh toggle.
// Uses Alpine.js for state management and setInterval for periodic refresh.
// Auto-refresh only fires when the browser tab is visible and no modal is open.
func RefreshButton() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"{ refreshing: false, auto: true, _iv: null }\" x-init=\"$nextTick(() => { _iv = setInterval(() => { if (auto && !document.hidden && !refreshing) { refreshing = true; window.location.reload(); } }, 30000); })\" x-on:beforeunload.window=\"clearInterval(_iv)\" class=\"flex items-center gap-1\"><button @click=\"refreshing = true; window.location.reload()\" class=\"p-2 text-gray-400 hover:text-white hover:bg-dark-700 rounded-lg transition-colors\" title=\"Refresh\"><i class=\"fas fa-sync-alt text-sm\" :class=\"refreshing && 'animate-spin'\"></i></button> <button @click=\"auto = !auto\" class=\"p-1.5 rounded-lg transition-colors\" :class=\"auto ? 'text-green-400 hover:bg-dark-700' : 'text-gray-500 hover:bg-dark-700'\" :title=\"auto ? 'Auto-refresh on (30s)' : 'Auto-refresh off'\"><i class=\"fas fa-circle\" style=\"font-size: 6px;\"></i></button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
